services:
  - type: web
    name: portfolio-site
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_site.wsgi:application --bind 0.0.0.0:$PORT
