"""
Django settings for portfolio_site project.

Generated by 'django-admin startproject' using Django 5.2.6.

See:
https://docs.djangoproject.com/en/5.2/topics/settings/
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
try:
    import dj_database_url
except Exception:
    dj_database_url = None

# load .env (if you use it)
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key")
DEBUG = os.getenv("DEBUG", "True") == "True"

# during dev you can use these hosts
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    # default django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # your app
    'portfolio.apps.PortfolioConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # whitenoise serves static files in production (optional in dev)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ensure Django searches your app templates folder
        'DIRS': [BASE_DIR / 'portfolio' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_site.wsgi.application'

# Database (sqlite for local dev)
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # Prefer dj-database-url when available (clean parsing and extras)
    if dj_database_url:
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
        }
    else:
        # Minimal fallback parser for common postgres URLs when dj-database-url is not installed
        from urllib.parse import urlparse, unquote

        url = urlparse(DATABASE_URL)
        # support postgres:// or postgresql://
        if url.scheme.startswith('postgres') or url.scheme.startswith('postgresql'):
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': unquote(url.path[1:]),
                    'USER': unquote(url.username) if url.username else '',
                    'PASSWORD': unquote(url.password) if url.password else '',
                    'HOST': url.hostname or '',
                    'PORT': url.port or '',
                }
            }
        else:
            # unknown scheme; fallback to sqlite to avoid crash in environments without dj-database-url
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
else:
    # Fallback to sqlite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
# set your timezone if you want (developer note: user's TZ Asia/Kolkata)
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# IMPORTANT: STATIC_URL must start with a slash
STATIC_URL = '/static/'

# Where Django will look for static files in development
# Primary static dir (recommended place for your static assets)
# and also include the templates subfolder that currently contains your css/images
# (quick fix: ideally move static files into `portfolio/static/` and remove the templates path)
STATICFILES_DIRS = [
    BASE_DIR / 'portfolio' / 'static',
    BASE_DIR / 'portfolio' / 'templates',
]

# Where collectstatic will copy static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise's compressed manifest storage to serve static files efficiently
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (dev)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@example.com'

# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_Rh6fsnuqQx2rkP')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'Hs7pwHiS4rOiGs98Uew4QImh')

# Debug: Print Razorpay configuration (remove in production)
if DEBUG:
    print(f"Loading Razorpay config - Key ID: {RAZORPAY_KEY_ID}")
    print(f"Loading Razorpay config - Secret: {RAZORPAY_KEY_SECRET[:8]}..." if RAZORPAY_KEY_SECRET else "No secret found")

# Payment Configuration
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', 'webhook_secret')
PAYMENT_SUCCESS_URL = '/payment/success/'
PAYMENT_FAILURE_URL = '/payment/failure/'
