# Generated by Django 4.2.26 on 2025-11-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_paymentorder_service_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('iot', 'IoT Projects'), ('automation', 'Automation'), ('ai-ml', 'AI/ML'), ('education', 'Educational'), ('other', 'Other')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('technologies', models.CharField(help_text='Comma separated list of technologies used', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
